baseURL = "https://www.tmuly.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "docs"

# example of config.toml
[params]
  highlightStyle = "github"

[[menu.main]]
  name   = "Usage"
  url    = "/usage/"
  weight = 10

[[menu.main]]
  name   = "News"
  url    = "/categories/news/"
  weight = 20